sudo: required
services:
    - docker

before_install:
    - docker build -t anoopsehdev/docker-react -f Dockerfile.dev .

script:
    - docker run CI=true anoopsehdev/docker-react npm test

deploy:
    provider: gae
    keyfile: "YOUR SERVICE ACCOUNT JSON FILE"
    project: "YOUR PROJECT ID"